Nlp
netcracker-education-center/data-collector pull request #13
Opened 2020-12-26 14:48 UTC by s4kh4rov

2020-12-27 14:11 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/springboot/Application.java
> +@ComponentScan(basePackages = "org.netcracker.learningcenter")
Move Application class to root or use @SpringBootApplication(scanBasePackages = "org.netcracker.learningcenter")

2020-12-27 14:20 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/utils/Pipeline.java
> +public class Pipeline {
Declare this class as Spring bean too, read about Spring Java based configuration

2021-01-13 16:15 UTC, kravchenko-da commented on src/main/java/org/netcracker/learningcenter/utils/TextSplittingCriteria.java
> +public enum TextSplittingCriteria {
Always a great idea to add some commentary (or better JavaDoc) to describe what enums mean or what one or another method does

2021-01-18 14:38 UTC, Fuzzzi requested changes

2021-01-18 14:38 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/config/NLPConfig.java
> +        String propertiesName = "tokenize, ssplit, pos, lemma, ner";
This definition of this field should be as a constant

2021-01-18 14:38 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/springboot/Controller.java
> +    @PostMapping(value = "/split", produces = "application/json")
Method GET used to request to get data without body 
Method POST used to send data to the server(register account, analyze data etc)
Learn more about using the HTTP methods GET, POST, DELETE, PUT.
Ask @ MajorPayne36 how to use POST methods correctly

2021-01-18 14:38 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/service/NLPService.java
> +                new AnnotationConfigApplicationContext(NLPConfig.class);
To work with the context, you need to create a new class that implements the singleton pattern.
read more:
https://javarush.ru/groups/posts/589-patternih-i-singleton--dlja-vsekh-kto-vpervihe-s-nimi-stolknulsja

2021-01-26 12:58 UTC, kravchenko-da commented on src/main/java/org/netcracker/learningcenter/controller/Controller.java
> +public class Controller {
Please be more specific, like "NlpController" or "TicketsController"

2021-01-27 15:26 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/controller/FTPController.java
> +        if (!jsonNode.path("dateFilter").isMissingNode()) {
Move field name to constants, you already use it twice

2021-01-27 15:27 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/controller/FTPController.java
> +                throw new Exception("Mandatory field is missing");
Do not use common Exception class, use or create more specific

2021-01-27 15:29 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/reader/DocxFileReader.java
> +            FileInputStream fis = new FileInputStream(file.getAbsolutePath());
Use try-with-resources for InputStream

2021-01-27 15:30 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/reader/DocxFileReader.java
> +            e.printStackTrace();
Do not just print stacktrace, throw your own exception or log if the exception is not critical

2021-01-27 15:31 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/reader/PdfFileReader.java
> +            document.close();
Try-with-resources too?

2021-01-27 15:32 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/reader/ReaderFactory.java
> +            throw new RuntimeException("No reader found for file " + filename + ".Unsupported extension.");
Use specific exception

2021-01-27 15:34 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/service/FTPService.java
> +        }
try-with-resources and do not just print stacktrace

2021-01-27 15:36 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/utils/FileUtils.java
> +            document.close();
try-with-resources

2021-01-27 15:36 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/utils/FtpClient.java
> +        outputStream1.close();
try-with-resources

2021-01-29 07:46 UTC, s4kh4rov commented on src/main/java/org/netcracker/learningcenter/controller/FTPController.java
> +        if (!jsonNode.path("dateFilter").isMissingNode()) {
Moved field name dateFilter and extensionFilter to constants

2021-01-29 07:48 UTC, s4kh4rov commented on src/main/java/org/netcracker/learningcenter/controller/FTPController.java
> +                throw new Exception("Mandatory field is missing");
Replaced Exception with ResourceNotFoundException

2021-01-29 07:50 UTC, s4kh4rov commented on src/main/java/org/netcracker/learningcenter/reader/DocxFileReader.java
> +            FileInputStream fis = new FileInputStream(file.getAbsolutePath());
Replaced try-catch with try-with-resource

2021-01-29 07:54 UTC, s4kh4rov commented on src/main/java/org/netcracker/learningcenter/reader/ReaderFactory.java
> +            throw new RuntimeException("No reader found for file " + filename + ".Unsupported extension.");
Created a new ReaderNotFound Exception and replaced RuntimeException with it

2021-01-29 07:55 UTC, s4kh4rov commented on src/main/java/org/netcracker/learningcenter/reader/PdfFileReader.java
> +            document.close();
Replaced try-catch with try-with-resource

2021-01-29 07:56 UTC, s4kh4rov commented on src/main/java/org/netcracker/learningcenter/utils/FileUtils.java
> +            document.close();
Replaced try-catch with try-with-resource

2021-01-29 07:58 UTC, s4kh4rov commented on src/main/java/org/netcracker/learningcenter/reader/TxtFileReader.java
> +    private static TxtFileReader instance;
Declare reader classes as Spring beans

2021-01-29 08:02 UTC, s4kh4rov commented on src/main/java/org/netcracker/learningcenter/service/FTPService.java
> +        }
Added AutoCloseable implementation for FtpClient class.Replacing try-catch with try-with-resource.Instead of printStackTrace added LOGGER.error(e)

2021-01-29 08:02 UTC, s4kh4rov commented on src/main/java/org/netcracker/learningcenter/reader/DocxFileReader.java
> +            e.printStackTrace();
Instead of printStackTrace added LOGGER.error(e)

2021-01-29 08:04 UTC, s4kh4rov commented on src/main/java/org/netcracker/learningcenter/utils/FtpClient.java
> +        outputStream1.close();
Added try-with-resource

2021-01-29 20:29 UTC, Fuzzzi requested changes

2021-01-29 20:29 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/reader/DocxFileReader.java
> +            LOGGER.error(e);
А зачем мы здесь ловим этот эксепшен? Мы же если пришло неверное расширение не сможем нормально отработать.
У нас опять же получается 2 путя:
1. Мы либо сначала проверяем расширение, которое пришло среди тех, которые поддерживаем, и если это не то - выбрасываем ошибку в респонс.
2. Либо мы эту ошибку не ловим нигде и она пробрасывается до самого верха и возвращается в респонсе

2021-01-29 20:29 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/reader/PdfFileReader.java
> +            LOGGER.error(e);
тоже самое что и выше

2021-01-29 20:29 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/reader/TxtFileReader.java
> +            LOGGER.error(e);
и тут тоже самое

2021-01-29 20:29 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/utils/FileUtils.java
> +                LOGGER.error(e);
Ну с логгированием в любом случае разберись. Потому что так не очень хорошо делать

2021-01-31 15:53 UTC, Fuzzzi approved these changes

2021-01-31 15:53 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/exceptions/ReaderNotFoundException.java
> +public class ReaderNotFoundException extends Exception {
Саш, забыл добавить @ResponseStatus(HttpStatus.NOT_FOUND), чтобы уходил корректный код ошибки

2021-02-03 08:27 UTC, Fuzzzi approved these changes

2021-02-03 16:07 UTC, Rubik0000 approved these changes

2021-02-03 16:07 UTC, merged