Feature dataminer controller
netcracker-education-center/data-collector pull request #24
Opened 2021-02-25 20:49 UTC by savin000

Everything works well. I ran into problems with properties value assignment. Values ​​from .properties file are not taken using getClass().getResourceAsStream()

2021-02-26 12:23 UTC, Fuzzzi requested changes

2021-02-26 12:23 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/controllers/DataMinerController.java
> +            } else if (jSource.asText().equals("FTP_FILE")) {
так у нас же может быть и JIRA и FTP одновременно

2021-02-26 12:23 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/services/DataMinerService.java
> +        try (InputStream inputStream = getClass().getResourceAsStream("/application.properties")) {
Посмотри про аннотацию @Value в спринге. Она используется чтобы доставать из пропертей поля и системные переменные

2021-02-28 19:14 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/controllers/DataMinerController.java
> +    @Autowired
Do not need autowired because it's infected via constructor

2021-02-28 19:16 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/controllers/DataMinerController.java
> +    public synchronized void searchAndCollect(@RequestBody JsonNode jsonNode) throws ResourceNotFoundException {
synchronized why?

2021-02-28 19:19 UTC, savin000 commented on src/main/java/org/netcracker/learningcenter/controllers/DataMinerController.java
> +    public synchronized void searchAndCollect(@RequestBody JsonNode jsonNode) throws ResourceNotFoundException {
removed

2021-02-28 19:19 UTC, savin000 commented on src/main/java/org/netcracker/learningcenter/controllers/DataMinerController.java
> +    @Autowired
ok, corrected

2021-02-28 19:24 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/services/DataMiner/DataMinerService.java
> +        properties.setProperty("port2", port2);
move to constants

2021-02-28 19:24 UTC, Rubik0000 approved these changes

2021-02-28 19:35 UTC, savin000 commented on src/main/java/org/netcracker/learningcenter/services/DataMiner/DataMinerService.java
> +        properties.setProperty("port2", port2);
moved

2021-03-01 11:02 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/jira/JiraClientWorker.java
> +                Promise<SearchResult> searchResult = restClient.getSearchClient().searchJql("description ~ " + "\"" + keyword + "\"");
я предлагаю использовать не description, а text
text вроде больший спект охватывает и ищет и в названии и в описании и в комментах
хотя тоже непонятно, насколько такое количество совпадений нам нужно

2021-03-01 12:27 UTC, Fuzzzi approved these changes

2021-03-01 12:27 UTC, merged