Feature kafka dataminer
netcracker-education-center/data-collector pull request #28
Opened 2021-03-17 14:47 UTC by savin000

Kafka consumer and producer added. Listener initiates search -> DataMiner service searches and collects data -> producer sends a message to the topic associated with analysis service with the results of the search.

2021-03-17 14:56 UTC, Fuzzzi requested changes

2021-03-17 14:56 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/kafka/dataminer/consumer/DataMinerConsumer.java
> +            LOG.error(e.getMessage());
Ну мы же говорили про логгирование ошибок, текст какой-то вменяемый необходим

2021-03-17 14:56 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/kafka/dataminer/consumer/DataMinerConsumerConfig.java
> +        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
у нас разве данные не в json формате приходят? если да, то можно сразу юзать JsonDeserializer

2021-03-17 14:57 UTC, Fuzzzi requested changes

2021-03-17 14:57 UTC, Fuzzzi commented on pom.xml
>          <dependency>
че за пустые лог файлы ты тащишь в репозиторий?

2021-03-17 14:59 UTC, savin000 commented on src/main/java/org/netcracker/learningcenter/kafka/dataminer/consumer/DataMinerConsumer.java
> +            LOG.error(e.getMessage());
А, извиняюсь, недоглядел, эту часть давно сделал прост

2021-03-17 15:00 UTC, savin000 commented on src/main/java/org/netcracker/learningcenter/kafka/dataminer/consumer/DataMinerConsumerConfig.java
> +        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
хорошо, поправлю

2021-03-17 15:03 UTC, savin000 commented on pom.xml
>          <dependency>
они с ветки Андраника тянутся

2021-03-18 07:38 UTC, Fuzzzi requested changes

2021-03-18 07:38 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/Application.java
> +            LOG.error(e);
сообщение))))

2021-03-18 07:38 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/controllers/DataMinerKafkaController.java
> +        userFuture.addCallback(System.out::println, System.err::println);
Погугли про метод addCallback. Сейчас ты результаты в консоль выводишь, смысла в этом особо нет. Нужно в лог

2021-03-18 20:51 UTC, Fuzzzi approved these changes

2021-03-18 21:07 UTC, merged